#!/usr/bin/env sh

# Big Sur fix
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# create and label spaces
yabai -m space 1 --label main
yabai -m space 3 --label chat
yabai -m space 2 --label mail

# mouse settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# window behavior
yabai -m config layout                       float
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off

# window opacity
yabai -m config window_opacity               off

# window borders
yabai -m config window_border                off

# window padding
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   20

# app location
yabai -m rule --add app='Firefox' space=main
yabai -m rule --add app='Mail' space=mail
yabai -m rule --add app='Mattermost' space=chat
yabai -m rule --add app='^Visual Studio Code$' space=code

