#!/usr/bin/env sh

# Swap windows
hyper - left : yabai -m window --warp west
hyper - down : yabai -m window --warp south
hyper - up : yabai -m window --warp north
hyper - right : yabai -m window --warp east

# Make window fullscreen
hyper - f         : yabai -m window --toggle zoom-fullscreen
hyper - g 		  : yabai -m window --toggle native-fullscreen

# Equalize size of windows
hyper - e : yabai -m space --balance

# Rotate clockwise
hyper - r         : yabai -m space --rotate 270

# Mirror on X and Y Axis
hyper - i : yabai -m space --mirror x-axis
hyper - u : yabai -m space --mirror y-axis

# Float / Unfloat window
hyper - y : \
    yabai -m window --toggle float; \
    yabai -m window --grid 5:5:1:1:3:3; \
    yabai -m window --toggle border

# Fill float
hyper - o : yabai -m window --grid 1:1:0:0:1:1

# Center float
hyper - p : yabai -m window --grid 5:5:1:1:3:3

# Move focus container to workspace
hyper - 0x21 : yabai -m window --space prev; yabai -m space --focus prev
hyper - 0x1E : yabai -m window --space next; yabai -m space --focus next
hyper - 1 : yabai -m window --space 1; yabai -m space --focus 1
hyper - 2 : yabai -m window --space 2; yabai -m space --focus 2
hyper - 3 : yabai -m window --space 3; yabai -m space --focus 3
hyper - 4 : yabai -m window --space 4; yabai -m space --focus 4


# Resize windows
hyper - h : yabai -m window --resize left:-50:0; \
                 yabai -m window --resize right:50:0
hyper - j : yabai -m window --resize bottom:0:50; \
                 yabai -m window --resize top:0:-50
hyper - k : yabai -m window --resize bottom:0:-50; \
                 yabai -m window --resize top:0:50
hyper - l : yabai -m window --resize left:50:0; \
                 yabai -m window --resize right:-50:0

# Quick restart
hyper - t : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"


